name: current_locale
description: Obtains Device Locale Information
version: 1.0.0+1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.easee.current_locale
        pluginClass: CurrentLocalePlugin
      ios:
        pluginClass: SwiftCurrentLocalePlugin
      web:
        pluginClass: CurrentLocaleWeb
        fileName: current_locale_web.dart
